name: Build Assets

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:

      ### Get the environment prepared
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      # Ensure we're using the values from .env.example
      - name: Copy .env file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Get the show on the road.
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Install NPM dependencies
        run: npm ci

      - name: Compile Assets
        run: npm run production
